---
# install ack-grep
- name: check if ack-grep is installed
  command: which ack-grep
  register: installed
  failed_when: installed.rc > 1
  changed_when: no

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 604800
  when: installed.rc != 0

- name: install ack-grep
  apt:
    name: ack-grep
    state: present
  when: installed.rc != 0
